---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo

  roles:
    - ifupdown2
    - frr
    # - sflow



- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown