
# This task configures /etc/network/interfaces on ifupdown2. The variables for
# which interfaces are neighbors and networks come from the group_vars/all file.
- name: configure /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  # debugger: on_failed
  notify: reload networking


#need this for dot1q
- name: allow multiple vlans
  lineinfile: 
    dest: /etc/sysctl.d/bridge.conf 
    regexp: '^(.*)net.bridge.bridge-allow-multiple-vlans(.*)$' 
    line: 'net.bridge.bridge-allow-multiple-vlans=1'
    backrefs: yes
  notify: reload networking